# Kubernetes Deployment Example for PostgreSQL Load Test Client

apiVersion: v1
kind: Secret
metadata:
  name: postgres-load-test-config
  namespace: default
type: Opaque
stringData:
  DB_HOST: "postgres-service.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "your_password_here"
  DB_NAME: "testdb"
  DB_SSL_MODE: "disable"
  DB_MAX_OPEN_CONNS: "50"
  DB_MAX_IDLE_CONNS: "10"
  DB_MIN_FREE_CONNS: "5"
  CONCURRENT_WRITERS: "20"
  TEST_RUN_DURATION: "600"
  BATCH_SIZE: "100"
  REPORT_INTERVAL: "10"
  INSERT_PERCENT: "70"
  UPDATE_PERCENT: "30"
  TABLE_NAME: "load_test_data"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-load-test
  namespace: default
spec:
  # Number of times to retry if the job fails
  backoffLimit: 1
  
  # Clean up completed jobs after 1 hour
  ttlSecondsAfterFinished: 3600
  
  template:
    metadata:
      labels:
        app: postgres-load-test
    spec:
      restartPolicy: Never
      
      containers:
      - name: load-test-client
        image: your-registry/load-test-client:latest
        imagePullPolicy: Always
        
        # Load all configuration from secret
        envFrom:
        - secretRef:
            name: postgres-load-test-config
        
        # Resource limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

---
# Alternative: Run as a CronJob for scheduled load tests
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-load-test-scheduled
  namespace: default
spec:
  # Run every day at 2 AM
  schedule: "0 2 * * *"
  
  # Keep last 3 successful and 1 failed job
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 7200
      
      template:
        metadata:
          labels:
            app: postgres-load-test-scheduled
        spec:
          restartPolicy: Never
          
          containers:
          - name: load-test-client
            image: your-registry/load-test-client:latest
            imagePullPolicy: Always
            
            envFrom:
            - secretRef:
                name: postgres-load-test-config
            
            # Override duration for nightly tests
            env:
            - name: TEST_RUN_DURATION
              value: "1800"  # 30 minutes
            - name: CONCURRENT_WRITERS
              value: "30"
            
            resources:
              requests:
                memory: "256Mi"
                cpu: "500m"
              limits:
                memory: "512Mi"
                cpu: "1000m"
            
            securityContext:
              runAsNonRoot: true
              runAsUser: 65534
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
